site_name: PyForms
pages:
- Home: 'index.md'
- Getting started:
	- 'The basic':'getting-started.md'
	- 'Use multiple windows':'multiple-windows.md'
	- 'Mdi applications':'mdi-applications.md'
- API: 
    - 'BaseWidget': 'api-documentation/basewidget.md'
    - 'Controls': 'api-documentation/controls.md'
- About: 'about/license.md'